bookstore/urls.py
#bookstore/urls.py
#Rolph Recto

from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView

from bookstore.models import Book, Author, Review
from bookstore.views import *

urlpatterns = patterns('bookstore.views',
    #index/homepage
    url(r'^$',
        TemplateView.as_view(template_name='bookstore/index.html'),
        name='index'),
    url(r'^index/?$',
        TemplateView.as_view(template_name='bookstore/index.html'),
        name='index'),

    #login user
    url(r'^login/?$',
        LoginView.as_view(),
        name='login'),

    #login success
    url(r'^login/success/?$',
        TemplateView.as_view(template_name='bookstore/login_success.html'),
        name='login_success'),

    #login user
    url(r'^logout/?$',
        LogoutView.as_view(),
        name='logout'),

    #list of reviews for a certain book
    url(r'^book/(?P<book_id>[0-9]+?)/?$',
        BookReviewListView.as_view(),
        name='book_review_list'
    ),

    #list of reviews for a certain user
    url(r'^user/(?P<user_id>[0-9]+?)/?$',
        UserReviewListView.as_view(),
        name='user_review_list'
    ),
    url(r'^user/(?P<username>.+?)/?$',
        UserReviewListView.as_view(),
        name='user_review_list'
    ),

    #list of books, sorted
    url(r'^books?/?$',
        BookListView.as_view(),
        name='book_list'
    ),
)

django_bookstore/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_bookstore.views.home', name='home'),
    # url(r'^django_bookstore/', include('django_bookstore.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    #bookstore app
    url(r'^bookstore/',
        include('bookstore.urls', namespace='bookstore', app_name='bookstore')
    ),
)

bookstore/models.py
#bookstore/models.py
#Rolph Recto

from django.contrib.auth.models import User
from django.db import models

from django.core.exceptions import ValidationError

from bookstore import util


class Author(models.Model):
    """Model class for authors"""

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.first_name + " " + self.last_name


class Book(models.Model):
    """Model class for books"""

    title = models.CharField(max_length=150)
    author = models.ForeignKey(Author)
    #we're assuming that no book is published before 0 A.D.
    publication_year = models.IntegerField(null=True,
        validators=[util.not_negative])

    def __unicode__(self):
        return self.title


class Review(models.Model):
    """Model class for user reviews of books"""

    user = models.ForeignKey(User)
    book = models.ForeignKey(Book)
    timestamp = models.DateTimeField()
    #what the user had to say about the book
    review_message = models.TextField()
    #ratings go from 1-5
    rating = models.IntegerField(
        choices=(
            (1, '1'),
            (2, '2'),
            (3, '3'),
            (4, '4'),
            (5, '5'),
        )
    )

    def __unicode__(self):
        return self.user.username + " : " + self.book.title

bookstore/forms.py
#bookstore/forms.py
#Rolph Recto

from django import forms
from django.contrib.auth import authenticate

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='Username')
    password = forms.CharField(max_length=100, widget=forms.PasswordInput())

    def clean(self):
        """authenticate the user info"""
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            #check if user is active
            if not user.is_active:
                raise forms.ValidationError('This account is disabled.')
        else:
            raise forms.ValidationError('Invalid user information.')

        return cleaned_data

bookstore/views.py
#bookstore/views.py
#Rolph Recto

from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.db.models import Avg
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth import authenticate, login, logout

from bookstore.models import Author, Book, Review
from bookstore.forms import LoginForm


class BookReviewListView(ListView):
    """View for a list of reviews for a book"""
    model = Review
    template_name = 'bookstore/book_review_list.html'

    def get_queryset(self):
        self.book = get_object_or_404(Book, pk=self.kwargs['book_id'])
        return Review.objects.filter(book=self.book)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(BookReviewListView, self).get_context_data(**kwargs)
        # Add in the book
        context['book'] = self.book
        agg_list = self.get_queryset().aggregate(Avg('rating'))
        context['average_rating'] = agg_list['rating__avg']
        return context


class UserReviewListView(ListView):
    """View for a list of reviews for a user"""
    model = Review
    template_name = 'bookstore/user_review_list.html'

    def get_queryset(self):
        #URLconf captured user id
        if 'user_id' in self.kwargs:
            self.user = get_object_or_404(User, pk=self.kwargs['user_id'])
        #URLconf captured username
        else:
            self.user = get_object_or_404(User, username=self.kwargs['username'])

        return Review.objects.filter(user=self.user)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(UserReviewListView, self).get_context_data(**kwargs)

        # Add in the user
        context['queried_user'] = self.user

        agg_list = self.get_queryset().aggregate(Avg('rating'))
        context['average_rating'] = agg_list['rating__avg']

        return context


class BookListView(ListView):
    """View for a list of books"""
    model = Book
    template_name = 'bookstore/book_list.html'

    def get_queryset(self):
        return (Book.objects.all()
            .annotate(Avg('review__rating'))
            .order_by('title'))


class LoginView(FormView):
    """View for the login page"""
    template_name = 'bookstore/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('bookstore:login_success')

    def form_valid(self, form):
        #try to log the user in
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        #no need to check user because we already authenticated it in the form
        login(self.request, user)

        return super(LoginView, self).form_valid(form)


class LogoutView(TemplateView):
    """View for the logout page"""
    template_name = 'bookstore/logout.html'

    def get_context_data(self, **kwargs):
        context = super(LogoutView, self).get_context_data(**kwargs)

        #log user out
        print self.request.user
        if self.request.user.is_authenticated():
            logout(self.request)
            context['logout_success'] = True
        #user wasn't logged in
        else:
            context['logout_success'] = False

        return context

bookstore/templates/base.html
<html>

<head>
<title>{% block title %}{% endblock %}</title>
</head>

<body>
<div id='content'>

{% block content %}
{% endblock %}
</div>
</body>

</html>

bookstore/templates/bookstore/book_list.html
{% extends 'base.html' %}

{% block title %}Book List{% endblock %}

{% block content %}

{% include 'user_nav.html' %}

<h1>Book List</h1>

{% if book_list %}
<h2>{{ book_list|length }} book{{ book_list|pluralize }} total</h2>
{% endif %}

{% for book in book_list %}
<div class="book" id="book-{{ forloop.counter }}">
<p>{{ book.title }} by {{ book.author }}</p>
{% if book.review__rating__avg %}
<p><i>Average rating: {{ book.review__rating__avg }}</i></p>
{% endif %}
</div>
<hr />
{% empty %}
<p>There are no books in the database.</p>
{% endfor %}

{% endblock %}

bookstore/templates/bookstore/book_review_list.html
{% extends 'base.html' %}

{% block title %}Review List for {{ book.title }} {% endblock %}

{% block content %}

{% include 'user_nav.html' %}

<h1>{{ book.title }}</h1>
<h2>by {{ book.author }}</h2>
{% if review_list %}
<h3>{{ review_list|length }} review{{ review_list|pluralize}}</h2>
<h3>Average rating: {{ average_rating }}</h3>
{% endif %}

{% for review in review_list %}
<div class="review" id="review-{{ forloop.counter }}">
<p>{{ review.user.username }} ({{ review.timestamp }})</p>
<p>{{ review.rating }} out of 5</p>
<p>
{{ review.review_message }}
</p>
</div>
{% empty %}
<p>There are no reviews for this book.</p>
{% endfor %}
{% endblock %}

bookstore/templates/bookstore/index.html
{% extends 'base.html' %}

{% block title %}Bookstore Home{% endblock %}

{% block content %}

{% include 'user_nav.html' %}

<h1>This is a bookstore.</h1>

<p>
{% url 'bookstore:user_review_list' username=user.username as url_user_review_list %}
<a href='{{ url_user_review_list }}'>Get list of reviews by <b>{{ user.username }}</b></a>
</p>

<p>
{% url 'bookstore:book_list' as url_book_list %}
<a href='{{ url_book_list }}'>Get list of books in the bookstore</a>
</p>

{% endblock %}

bookstore/templates/bookstore/login.html
{% extends 'base.html' %}

{% block title %}Bookstore Login{% endblock %}

{% block content %}
<h1>Login</h1>

{% if user.is_authenticated %}
<p>
You are already logged in as <b>{{ user.username }}.</b>
</p>
{% else %}
<form action="" method="POST">
	{% csrf_token %}
	
	{{ form.errors }}
	<div>
	{{ form.username.label }} : {{ form.username }}
	{{ form.username.errors }}
	</div>
	<div>
	{{ form.password.label }} : {{ form.password }}
	{{ form.password.errors }}
	</div>
	<div>
	<input type="submit" value="Submit">
	</div>
</form>
{% endif %}

{% endblock %}

bookstore/templates/bookstore/login_success.html
{% extends 'base.html' %}

{% block title %}Bookstore Login{% endblock %}

{% block content %}
<h1>Login</h1>

{% if user.is_authenticated %}
<p>
You have successfully logged in as <b>{{ user.username }}.</b>
</p>
<p>
<a href="{% url 'bookstore:index' %}">Return to home</a>
</p>
{% else %}
<p>You are not logged in. Go <a href="{% url 'bookstore:login' %}">here</a> to log in.</p>
{% endif %}

{% endblock %}

bookstore/templates/bookstore/logout.html
{% extends 'base.html' %}

{% block title %}Bookstore Logout{% endblock %}

{% block content %}
<h1>Logout</h1>

{% if logout_success %}
<p>
You have successfully logged out. {{ user.username }}
{% url 'bookstore:index' as url_index %}
Go back to <a href='{{ url_index }}'>home</a>
</p>
{% else %}
<p>
You are not logged in.
</p>
{% url 'bookstore:login' as login_url %}
<a href='{{ login_url }}'>Login</a>
{% endif %}

{% endblock %}

bookstore/templates/bookstore/user_review_list.html
{% extends 'base.html' %}

{% block title %}Review List for {{ queried_user.username }} {% endblock %}

{% block content %}

{% include 'user_nav.html' %}

<h1>{{ queried_user.username }}</h1>
{% if review_list %}
<h3>{{ review_list|length }} review{{ review_list|pluralize}}</h2>
<h3>Average rating: {{ average_rating }}</h3>
{% endif %}

{% for review in review_list %}
<div class="review" id="review-{{ forloop.counter }}">
<p>{{ review.book.title }} ({{ review.timestamp }})</p>
<p>{{ review.rating }} out of 5</p>
<p>
{{ review.review_message }}
</p>
</div>
{% empty %}
<p>There are no reviews for this user.</p>
{% endfor %}
{% endblock %}

bookstore/templates/user_nav.html
{% url 'bookstore:index' as url_bookstore_index %}

{% if not user.is_anonymous %}
<h2>{{ user.username }}</h2>

<p>
<a href='{{ url_bookstore_index }}'>Home</a>
</p>

<p>
{% url 'bookstore:logout' as logout_url %}
<a href='{{ logout_url }}'>Logout</a>
</p>

{% else %}
<p>
You are not logged in.
</p>

<p>
<a href='{{ url_bookstore_index }}'>Home</a>
</p>

<p>
{% url 'bookstore:login' as login_url %}
<a href='{{ login_url }}'>Login</a>
</p>
{% endif %}